#ifndef SNAZZCRAFT_KEYS_H
#define SNAZZCRAFT_KEYS_H

#include "../../../../../includes/glfw3.h"

// Printable keys
#define SNAZZCRAFT_KEY_A (0x00)
#define SNAZZCRAFT_KEY_B (0x01)
#define SNAZZCRAFT_KEY_C (0x02)
#define SNAZZCRAFT_KEY_D (0x03)
#define SNAZZCRAFT_KEY_E (0x04)
#define SNAZZCRAFT_KEY_F (0x05)
#define SNAZZCRAFT_KEY_G (0x06)
#define SNAZZCRAFT_KEY_H (0x07)
#define SNAZZCRAFT_KEY_I (0x08)
#define SNAZZCRAFT_KEY_J (0x09)
#define SNAZZCRAFT_KEY_K (0x0A)
#define SNAZZCRAFT_KEY_L (0x0B)
#define SNAZZCRAFT_KEY_M (0x0C)
#define SNAZZCRAFT_KEY_N (0x0D)
#define SNAZZCRAFT_KEY_O (0x0E)
#define SNAZZCRAFT_KEY_P (0x0F)
#define SNAZZCRAFT_KEY_Q (0x10)
#define SNAZZCRAFT_KEY_R (0x11)
#define SNAZZCRAFT_KEY_S (0x12)
#define SNAZZCRAFT_KEY_T (0x13)
#define SNAZZCRAFT_KEY_U (0x14)
#define SNAZZCRAFT_KEY_V (0x15)
#define SNAZZCRAFT_KEY_W (0x16)
#define SNAZZCRAFT_KEY_X (0x17)
#define SNAZZCRAFT_KEY_Y (0x18)
#define SNAZZCRAFT_KEY_Z (0x19)

#define SNAZZCRAFT_KEY_0 (0x1A)
#define SNAZZCRAFT_KEY_1 (0x1B)
#define SNAZZCRAFT_KEY_2 (0x1C)
#define SNAZZCRAFT_KEY_3 (0x1D)
#define SNAZZCRAFT_KEY_4 (0x1E)
#define SNAZZCRAFT_KEY_5 (0x1F)
#define SNAZZCRAFT_KEY_6 (0x20)
#define SNAZZCRAFT_KEY_7 (0x21)
#define SNAZZCRAFT_KEY_8 (0x22)
#define SNAZZCRAFT_KEY_9 (0x23)

// Function keys
#define SNAZZCRAFT_KEY_ESCAPE       (0x24)
#define SNAZZCRAFT_KEY_LEFT_SHIFT   (0x25)
#define SNAZZCRAFT_KEY_RIGHT_SHIFT  (0x26)
#define SNAZZCRAFT_KEY_SPACE        (0x27)
#define SNAZZCRAFT_KEY_ENTER        (0x28)

#define SNAZZCRAFT_KEY_CHECK_AMOUNT (0x29)

const unsigned short SnazzCraftKeyToGLFWKey[SNAZZCRAFT_KEY_CHECK_AMOUNT] = {
    GLFW_KEY_A,
    GLFW_KEY_B,
    GLFW_KEY_C,
    GLFW_KEY_D,
    GLFW_KEY_E,
    GLFW_KEY_F,
    GLFW_KEY_G,
    GLFW_KEY_H,
    GLFW_KEY_I,
    GLFW_KEY_J,
    GLFW_KEY_K,
    GLFW_KEY_L,
    GLFW_KEY_M,
    GLFW_KEY_N,
    GLFW_KEY_O,
    GLFW_KEY_P,
    GLFW_KEY_Q,
    GLFW_KEY_R,
    GLFW_KEY_S,
    GLFW_KEY_T,
    GLFW_KEY_U,
    GLFW_KEY_V,
    GLFW_KEY_W,
    GLFW_KEY_X,
    GLFW_KEY_Y,
    GLFW_KEY_Z,

    GLFW_KEY_0,
    GLFW_KEY_1,
    GLFW_KEY_2,
    GLFW_KEY_3,
    GLFW_KEY_4,
    GLFW_KEY_5,
    GLFW_KEY_6,
    GLFW_KEY_7,
    GLFW_KEY_8,
    GLFW_KEY_9,

    GLFW_KEY_ESCAPE,
    GLFW_KEY_LEFT_SHIFT,
    GLFW_KEY_RIGHT_SHIFT,
    GLFW_KEY_SPACE,
    GLFW_KEY_ENTER
};

#endif // SNAZZCRAFT_KEYS_H
