#ifndef SNAZZCRAFT_EVENTS_H
#define SNAZZCRAFT_EVENTS_H

#define SNAZZCRAFT_EVENT_KEY_DOWN                  (0x00)
#define SNAZZCRAFT_EVENT_KEY_UP                    (0x01)
#define SNAZZCRAFT_EVENT_MOUSE_MOVE                (0x02)
#define SNAZZCRAFT_EVENT_MOUSE_CLICK_LEFT_PRESS    (0x03)
#define SNAZZCRAFT_EVENT_MOUSE_CLICK_LEFT_RELEASE  (0x04)
#define SNAZZCRAFT_EVENT_MOUSE_CLICK_RIGHT_PRESS   (0x05)
#define SNAZZCRAFT_EVENT_MOUSE_CLICK_RIGHT_RELEASE (0x06)

#endif // SNAZZCRAFT_EVENTS_H